services:
    psmever-service:
        build:
            context: './docker'
            dockerfile: Dockerfile
        environment:
            TZ: "Asia/Seoul"
        container_name: psmever-service
        hostname: psmever
        domainname: localdomain
        ports:
            - "9000:80"
            - "9001:8001"
            - "9003:443"
        stdin_open: true
        tty: true
        volumes:
            - .:/var/www/service:rw
            - ./docker/data:/tmp/data
        command:
            - /usr/local/bin/start.sh
        networks:
            - psmever-networks

networks:
    psmever-networks:
        driver: bridge
